[tox]
requires =
    tox>=4.32
env_list =
    lint
    py{311-315}

[testenv]
package = skip
pass_env =
    FORCE_COLOR
commands =
    {envpython} -m pytest \
      --cov timesheet \
      --cov tests \
      --cov-report html \
      --cov-report term \
      --cov-report xml \
      {posargs}
dependency_groups =
    tests

[testenv:lint]
skip_install = true
deps =
    prek
commands =
    prek run --all-files --show-diff-on-failure
